//Aarlyn
//Rylan
#include "stm32l476xx.h"
#include "ssd1306.h"
#include "ssd1306_fonts.h"

// Function prototypes
static void System_Clock_Init(void);
void I2C_Init(void);



int main(void) {
    // Initialize clocks
	System_Clock_Init();
	I2C_Init();
	ssd1306_Init();
	ssd1306_Fill(Black);
	ssd1306_SetCursor(0,0);
	ssd1306_UpdateScreen();
	ssd1306_WriteString("Welcome to",Font_7x10,White);
	ssd1306_UpdateScreen();
	ssd1306_SetCursor(0,20);
	ssd1306_WriteString("EECE 344 class!",Font_7x10,White);
	ssd1306_UpdateScreen();

}



static void System_Clock_Init(void) {
	// Set flash wait states to 4 to compensate for high clock speed
	FLASH->ACR = (FLASH->ACR & ~FLASH_ACR_LATENCY) | FLASH_ACR_LATENCY_4WS;
	// Enable HSI16
	RCC->CR |= RCC_CR_HSION;
	// Wait for HSI16 to be ready
	while(!(RCC->CR & RCC_CR_HSIRDY));
	// Disable the PLL to allow configuration
	RCC->CR &= ~RCC_CR_PLLON;
	// Wait for PLL to be fully disabled
	while(RCC->CR & RCC_CR_PLLRDY);
	// Configure PLL: HSI16 as source, divide by 1, multiply by 9, divide by 2 to give 72MHz output,
	// all outputs off
	RCC->PLLCFGR = (RCC->PLLCFGR
			& ~(RCC_PLLCFGR_PLLSRC | RCC_PLLCFGR_PLLR | RCC_PLLCFGR_PLLN | RCC_PLLCFGR_PLLM
					| RCC_PLLCFGR_PLLQEN | RCC_PLLCFGR_PLLPEN | RCC_PLLCFGR_PLLREN))
			| (0b10UL << RCC_PLLCFGR_PLLSRC_Pos) //HSI16 source
			| (9UL << RCC_PLLCFGR_PLLN_Pos); // multiply by 9 (divisions by 1 and 2 set by clears)
	// Enable PLL
	RCC->CR |= RCC_CR_PLLON;
	// Wait for PLL to be fully enabled
	while (!(RCC->CR & RCC_CR_PLLRDY));
	// Enable PLLR output (primary output)
	RCC->PLLCFGR |= RCC_PLLCFGR_PLLREN;
	// Select PLL as system clock
	RCC->CFGR = (RCC->CFGR & ~RCC_CFGR_SW) | RCC_CFGR_SW_PLL;
	// Wait for clock switch to be complete
	while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL);
}

// Initialize I2C1 for communication with the LCD screen.
// Configuration is controller mode, fast mode, with the peripheral address set to 0x3C.
void I2C_Init(void) {
	// Enable clock to port B
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOBEN;
	// Set PB8 and PB9 to alternate function 4, I2C1
	GPIOB->MODER = (GPIOA->MODER & ~(GPIO_MODER_MODE8 | GPIO_MODER_MODE9))
			| (0b10UL << GPIO_MODER_MODE8_Pos) | (0b10UL << GPIO_MODER_MODE9_Pos);
	GPIOB->AFR[1] = (GPIOA->AFR[1] & ~(GPIO_AFRH_AFSEL8 | GPIO_AFRH_AFSEL9))
			| (4UL << GPIO_AFRH_AFSEL8_Pos) | (4UL << GPIO_AFRH_AFSEL9_Pos);
	// Set PB8 and PB9 to high-speed, open-drain, pull-up
	GPIOB->OSPEEDR = (GPIOB->OSPEEDR & ~(GPIO_OSPEEDR_OSPEED8 | GPIO_OSPEEDR_OSPEED9))
			| (0b11UL << GPIO_OSPEEDR_OSPEED8_Pos) | (0b11UL << GPIO_OSPEEDR_OSPEED9_Pos);
	GPIOB->OTYPER |= GPIO_OTYPER_OT8 | GPIO_OTYPER_OT9;
	GPIOB->PUPDR = (GPIOB->PUPDR & ~(GPIO_PUPDR_PUPD8 | GPIO_PUPDR_PUPD9))
			| (0b01UL << GPIO_PUPDR_PUPD8_Pos) | (0b01UL << GPIO_PUPDR_PUPD9_Pos);
	// Select SYSCLK (72MHz) as I2C1 input
	RCC->CCIPR = (RCC->CCIPR & ~(RCC_CCIPR_I2C1SEL))
			| ((0b01 << RCC_CCIPR_I2C1SEL_Pos));
	// Enable I2C1 clock
	RCC->APB1ENR1 |= RCC_APB1ENR1_I2C1EN;
	// Set TIMINGR for fast mode, 72MHz input clock (constant generated by STM32CubeMX)
	// standard: 0x10C18DCC
	// fast: 0x00E12573
	I2C1->TIMINGR = 0x00E12573;
	// Enable I2C1
	I2C1->CR1 |= I2C_CR1_PE;
	// Set peripheral address to 0x3C, the LCD's address
	I2C1->CR2 = (I2C1->CR2 & ~(I2C_CR2_SADD))
			| (0x3CUL << (I2C_CR2_SADD_Pos + 1)); //SADD[0] is a don't care in 7-bit addressing mode
}

